from __future__ import annotations

import os
import sqlite3
import unittest
from unittest.mock import patch

from outlook_web import db_postgres_compat as compat


class PostgresCompatSqlTranslationTests(unittest.TestCase):
    def tearDown(self) -> None:
        compat.restore_sqlite_connect_for_tests()

    def test_no_database_url_keeps_sqlite_connect(self):
        original = sqlite3.connect
        with patch.dict(os.environ, {}, clear=True):
            self.assertFalse(compat.install_postgres_sqlite_compat())
        self.assertIs(sqlite3.connect, original)

    def test_unsupported_database_url_scheme_fails_before_patching(self):
        with patch.dict(os.environ, {"DATABASE_URL": "mysql://example"}, clear=True):
            with self.assertRaises(RuntimeError):
                compat.install_postgres_sqlite_compat()

    def test_qmark_placeholders_ignore_string_literals(self):
        sql = compat.translate_sqlite_sql(
            "SELECT * FROM settings WHERE key = ? AND value != '?' AND note = \"?\""
        )
        self.assertEqual(
            sql,
            "SELECT * FROM settings WHERE key = %s AND value != '?' AND note = \"?\"",
        )

    def test_insert_or_replace_settings_becomes_postgres_upsert(self):
        sql = compat.translate_sqlite_sql(
            """
            INSERT OR REPLACE INTO settings (key, value, updated_at)
            VALUES (?, ?, CURRENT_TIMESTAMP)
            """
        )
        self.assertIn("INSERT INTO settings", sql)
        self.assertIn("ON CONFLICT (key) DO UPDATE", sql)
        self.assertIn("VALUES (%s, %s, CURRENT_TIMESTAMP)", sql)

    def test_insert_or_replace_temp_messages_uses_message_unique_key(self):
        sql = compat.translate_sqlite_sql(
            """
            INSERT OR REPLACE INTO temp_email_messages
            (message_id, email_address, subject)
            VALUES (?, ?, ?)
            """
        )
        self.assertIn("INSERT INTO temp_email_messages", sql)
        self.assertIn("ON CONFLICT (email_address, message_id)", sql)
        self.assertIn("subject = EXCLUDED.subject", sql)

    def test_insert_or_ignore_becomes_do_nothing(self):
        sql = compat.translate_sqlite_sql(
            "INSERT OR IGNORE INTO settings (key, value) VALUES (?, ?)"
        )
        self.assertEqual(
            sql,
            "INSERT INTO settings (key, value) VALUES (%s, %s) ON CONFLICT DO NOTHING",
        )

    def test_sqlite_schema_fragments_become_postgres_compatible(self):
        sql = compat.translate_sqlite_sql(
            """
            CREATE TABLE IF NOT EXISTS sample (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                email_domain TEXT COLLATE NOCASE,
                created_at REAL DEFAULT (unixepoch('now'))
            )
            """
        )
        self.assertIn("INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql)
        self.assertNotIn("COLLATE NOCASE", sql)
        self.assertIn("EXTRACT(EPOCH FROM NOW())", sql)


if __name__ == "__main__":
    unittest.main()
